apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      name: tcp-postgresql
  selector:
    app: db