services:
  db:
    build: .\src\main\resources\db\
    image: db:v1
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - app_network
  java_app:
    build: .
    image: app:v1
    container_name: java_app
    ports:
      - "8080:8080"
    environment:
      - GREETING_TEXT=Docker
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=postgres
      - DB_PASS=db_pass
    volumes:
      - ./external/:/home/app/
    networks:
      - app_network
    depends_on:
      - db
networks:
  app_network: {}