apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      name: http
  selector:
    app: app-server